spring: 
  profiles: local

# Redis 配置（2.x/3.x）
redis:
  enabled: true
  host: localhost
  port: 6379
  database: 0
  password: 1234
  pool:
    maxIdle: 3
    maxTotal: 20

jdbc: 
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/frp?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
  username: root
  password: root
  testSql: SELECT 1
