
#============================#
#===== Project settings =====#
#============================#

# 产品或项目名称、软件开发公司名称
productName: Frp
companyName: Jo

# 产品版本、版权年份
productVersion: V1.0
copyrightYear: 2018

#是否演示模式
demoMode: false

